### ISSUE TITLE
Can't wrap e_charts in a function

### ISSUE THREAD

**Issue by dickoa** [JohnCoene/echarts4r#6]
Hi,

Thanks for this great package, I wanted to play a little bit with it  and I came across something odd.
Here is a reprex

```r
library(echarts4r)
set.seed(1)
df <- data.frame(date = c("2018-01-01", "2018-01-02"),
                x = rnorm(n = 2, mean = 4),
                y = rnorm(n = 2, mean = 5))

f <- function(mycolname) {
  df %>%
    e_charts(date) %>%
    e_area(mycolname)
}

f("x")
Error in FUN(X[[i]], ...) : object 'mycolname' not found

mycolname <- "y"
f("x") ## it 'works' but uses the global value ("y") not the one in the function scope "x"
```

I wanted to know if it's a bug or feature and what's the best way to create wrapper functions.
 
Thanks again

#### Session info

```r
Session info ---------------------------------------------------
 setting  value                                      
 version  R version 3.5.0 Patched (2018-04-28 r74669)
 system   x86_64, linux-gnu                          
 ui       X11                                        
 language (EN)                                       
 collate  en_US.UTF-8                                
 tz       Africa/Dakar                               
 date     2018-05-04                                 

Packages -------------------------------------------------------
 package     * version    date      
 assertthat    0.2.0      2017-04-11
 base        * 3.5.0      2018-04-28
 bindr         0.1.1      2018-03-13
 bindrcpp      0.2.2      2018-03-29
 compiler      3.5.0      2018-04-28
 crosstalk     1.0.0      2016-12-21
 datasets    * 3.5.0      2018-04-28
 devtools      1.13.5     2018-02-18
 digest        0.6.15     2018-01-28
 dplyr         0.7.4      2017-09-28
 echarts4r   * 0.0.1      2018-05-04
 glue          1.2.0      2017-10-29
 graphics    * 3.5.0      2018-04-28
 grDevices   * 3.5.0      2018-04-28
 htmltools     0.3.6      2017-04-28
 htmlwidgets   1.2.1      2018-05-02
 httpuv        1.4.2      2018-05-03
 jsonlite      1.5        2017-06-01
 later         0.7.2      2018-05-01
 magrittr      1.5        2014-11-22
 memoise       1.1.0      2017-04-21
 methods     * 3.5.0      2018-04-28
 mime          0.5        2016-07-07
 pillar        1.2.2      2018-04-26
 pkgconfig     2.0.1      2017-03-21
 promises      1.0.1      2018-04-13
 R6            2.2.2      2017-06-17
 Rcpp          0.12.16    2018-03-13
 rlang         0.2.0.9001 2018-04-30
 shiny         1.0.5      2017-08-23
 stats       * 3.5.0      2018-04-28
 tibble        1.4.2      2018-01-22
 utils       * 3.5.0      2018-04-28
 withr         2.1.2      2018-04-29
 xtable        1.8-2      2016-02-05
 yaml          2.1.19     2018-05-01
 source                               
 CRAN (R 3.5.0)                       
 local                                
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 local                                
 CRAN (R 3.5.0)                       
 local                                
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 Github (JohnCoene/echarts4r@f19bf67) 
 CRAN (R 3.5.0)                       
 local                                
 local                                
 CRAN (R 3.5.0)                       
 Github (ramnathv/htmlwidgets@e3097fa)
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 local                                
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       
 Github (r-lib/rlang@82b2727)         
 CRAN (R 3.5.0)                       
 local                                
 CRAN (R 3.5.0)                       
 local                                
 Github (jimhester/withr@79d7b0d)     
 CRAN (R 3.5.0)                       
 CRAN (R 3.5.0)                       

```

**Comment by JohnCoene** [comment]
Hey, thanks for kind comment.

It's not an issue per se, the reason is does not work is not because it is wrapped in a function but because you pass the argument as a string, which would not work outside of a function either.

```r
# does not work
mtcars %>%
  e_charts(qsec) %>%
  e_line("mpg")
```
You need to pass the argument as quosure. I'm not in front of a laptop now but this should work.

```r
mtcars %>%
  e_charts(qsec) %>%
  e_line(!!rlang::sym("mpg"))
```

Wrap it like that in your function.

**Comment by dickoa** [comment]
Thank for the prompt reply, I tried to play with rlang too without success.
However, this code works

```r
mtcars %>%
  e_charts(qsec) %>%
  e_line("mpg")
```
and I can't use tidy eval with it, let me know when you can test.

```r
library(rlang)
f <- function(var) {
  var <- enquo(var)
  df %>%
    e_charts(date) %>%
    e_area(!! var)
}

f(x)
## Error in !var : invalid argument type

f2 <- function(var_string) {
  var <- sym(var_string)
  df %>%
    e_charts(date) %>%
    e_area(!! var)
}

f2("x")
## Error in !var : invalid argument type
```

Thanks

**Comment by dickoa** [comment]
Thanks John for this solution, but it looks like we also need a `e_charts_` function

```r
library(echarts4r)
plot_echarts <- function(data, x1, x2){
    data %>%
        e_charts(x1) %>%
        e_bar_(x2)
}

df <- data.frame(x = LETTERS[1:5], y = runif(5))

# pass as string 
plot_echarts(df, "x", "y")
## Error in arrange_impl(.data, dots) : 
##   Evaluation error: object 'x1' not found.
```
I will take a look at the code to better understand and see if I can be more helpful.

Thanks

**Comment by JohnCoene** [comment]
Hey dickoa, thanks for bearing with me on this one. Should work now, you can use `e_charts_`.

**Comment by dickoa** [comment]
Thanks John, I will wait for few days to test it again then.
I still don't have access to `e_charts_`

```r
## using the latest version on master as of 9th May 1:00 PM UTC
echarts4r:::e_charts_
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'e_charts_' not found
```

**Comment by JohnCoene** [comment]
Apologies, thought I had pushed it, I hadn't, it's good now.

**Comment by dickoa** [comment]
Working now thanks a lot John for this great package

**Comment by JohnCoene** [comment]
@dickoa I'll go ahead and closed this, all escape hatches (ending in `_`) have now been added. If there is no escape hatch for a function it is because it is not needed.

Feel free to re-open if you encounter an issue.
